# Agent DSL calls are kept without parentheses in authored modules.
agent_locals = [
  agent: 1,
  routes: 1,
  route: 2,
  route: 3,
  define: 1,
  define: 2,
  plugin: 1,
  plugin: 2,
  schema: 1,
  metadata: 1,
  max_state_size: 1,
  defaults: 1,
  priority: 1,
  match: 1,
  signal_source: 1,
  topology: 1,
  agents: 1,
  agent: 2,
  agent: 3,
  group: 2,
  group: 3,
  resources: 1,
  bus: 1,
  bus: 2,
  relationships: 1,
  owns: 2,
  owns: 3,
  connections: 1,
  subscribe: 2,
  startup: 1,
  initial_state: 1,
  depends_on: 1,
  count: 1,
  members: 1,
  key_by: 1,
  config: 1,
  on_parent_exit: 1,
  concurrency: 1,
  ready: 1,
  max_agents: 1,
  retry_interval: 1,
  task_timeout: 1,
  topologies: 1,
  include: 2,
  include: 3,
  inputs: 1,
  bind: 2,
  imports: 1,
  exports: 1
]

# Used by "mix format"
[
  import_deps: [:jido_action],
  locals_without_parens: agent_locals,
  export: [locals_without_parens: agent_locals],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
