defmodule Jido.Topology.Signal do
  @moduledoc """
  Contains the custom lifecycle Signal modules used by a Topology Controller.

  A Controller sends these Signals to its optional lifecycle Agent. Delivery
  is best effort and cannot change activation, repair, update, or cleanup.
  Policy belongs in normal Agent routes and Plugins.

  The public types are:

  - `jido.topology.lifecycle.operation.started`
  - `jido.topology.lifecycle.operation.completed`
  - `jido.topology.lifecycle.component.ready`
  - `jido.topology.lifecycle.component.failed`
  - `jido.topology.lifecycle.status.changed`

  Each type has one custom Signal module:

  - `Jido.Topology.Signal.OperationStarted`
  - `Jido.Topology.Signal.OperationCompleted`
  - `Jido.Topology.Signal.ComponentReady`
  - `Jido.Topology.Signal.ComponentFailed`
  - `Jido.Topology.Signal.StatusChanged`

  Use the `new/2`, `new!/2`, `type/0`, and `schema/0` functions generated by
  `Jido.Signal`. This namespace does not define separate Signal factory
  functions.

  All data contains `topology_id` and `operation_id`. Operation Signals add the
  operation and result status. Component Signals add the plan key, kind, and
  Erlang node. Failure data contains one bounded reason code, not the original
  error value.
  """

  @signals [
    Jido.Topology.Signal.OperationStarted,
    Jido.Topology.Signal.OperationCompleted,
    Jido.Topology.Signal.ComponentReady,
    Jido.Topology.Signal.ComponentFailed,
    Jido.Topology.Signal.StatusChanged
  ]

  @doc "Returns the supported topology lifecycle Signal types."
  @spec types() :: [String.t()]
  def types, do: Enum.map(@signals, & &1.type())
end
