defmodule Jido.EasyAgent.RuntimeAgent do
  @moduledoc """
  A dynamically configurable Agent module for EasyAgent.

  This module serves as the runtime Agent implementation that EasyAgent
  uses behind the scenes. It's designed to be flexible and work with
  runtime configuration rather than compile-time schemas.
  """

  use Jido.Agent,
    name: "easy_agent_runtime",
    description: "Runtime agent for EasyAgent wrapper",
    schema: [
      # Keep schema minimal for maximum flexibility
      name: [type: :string, required: true],
      reasoner: [type: :atom, required: true],
      max_turns: [type: :integer, default: 10],
      conversation: [type: {:list, :map}, default: []],
      turn: [type: :integer, default: 0]
    ],
    actions: [
      # Start with basic actions that are commonly useful
      Jido.Skills.Arithmetic.Actions.Eval
    ]

  # The new/2 function is automatically generated by the Jido.Agent macro
  # It will merge the initial_state with schema defaults
end
